// Code generated by mockery v2.52.4. DO NOT EDIT.

package outbox

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockProducer is an autogenerated mock type for the Producer type
type MockProducer struct {
	mock.Mock
}

// Send provides a mock function with given fields: ctx, topic, key, val
func (_m *MockProducer) Send(ctx context.Context, topic string, key []byte, val []byte) error {
	ret := _m.Called(ctx, topic, key, val)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, []byte, []byte) error); ok {
		r0 = rf(ctx, topic, key, val)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockProducer creates a new instance of MockProducer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProducer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProducer {
	mock := &MockProducer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
